# Creating service containers

services:
  postgresql:
    image: postgres
    container_name: postgresql_container
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: 1234 
      POSTGRES_DB: decanaria
    ports:
      - '5432:5432'
    volumes:
      - postgresql:/var/lib/postgresql/data

  mongodb:
    image: mongo
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - 27017:27017
    volumes:
      - mongodb_volume:/data/db
  
  redis:
    image: redis/redis-stack-server
    container_name: redis_container
    environment:
      - REDIS_ARGS="--save 60 500"
    ports:
      - 6379:6379
    volumes:
    - redis-storage-data:/data/redis

  scrapyspiders:
    container_name: scrapy_spiders_container
    build:
      context: ./


# Creating volumes for databases to use

volumes:
  postgresql:
    driver: local
  mongodb_volume:
  redis-storage-data: