import scrapy

class TestItem(scrapy.Item):
    latitude = scrapy.Field()


class JobsItem(scrapy.Item):
    slug = scrapy.Field()
    language = scrapy.Field()
    languages = scrapy.Field()
    req_id = scrapy.Field()
    title = scrapy.Field()
    description = scrapy.Field()
    street_address = scrapy.Field()
    city = scrapy.Field()
    state = scrapy.Field()
    country_code = scrapy.Field()
    postal_code = scrapy.Field()
    location_type = scrapy.Field()
    latitude = scrapy.Field()
    longitude = scrapy.Field()
    categories = scrapy.Field()
    brand = scrapy.Field()
    department = scrapy.Field()
    recruiter_id = scrapy.Field()
    promotion_value = scrapy.Field()
    salary_value = scrapy.Field()
    salary_min = scrapy.Field()
    salary_max = scrapy.Field()
    employment_type = scrapy.Field()
    source = scrapy.Field()
    posted_date = scrapy.Field()
    posting_expiry_date = scrapy.Field()
    apply_url = scrapy.Field()
    is_internal = scrapy.Field()
    is_searchable = scrapy.Field()
    is_applyable = scrapy.Field()
    is_li_easy_applyable = scrapy.Field()
    ats_code = scrapy.Field()
    meta_data = scrapy.Field()
    update_date = scrapy.Field()
    create_date = scrapy.Field()
    category = scrapy.Field()
    full_location = scrapy.Field()
    short_location = scrapy.Field()
